name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
      
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server
    
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        CA_PATH: /home/runner 
        REDIS_URL: redis:${{ job.services.redis.ports[6379] }} 
      run: go test -v ./...
